### ISSUE TITLE
Set serde is_human_readable to False

### ISSUE THREAD

**Issue by sevnx** [jhelovuo/cdr-encoding#1]
## Summary

The current implementation of the CDR (Common Data Representation) Serializer and Deserializer does not override the default implementation of the `is_human_readable` method, which returns `true`. This is inconsistent with CDR's nature as a binary format and limits the flexibility of serialization/deserialization for human-readable formats like JSON or YAML.

## Need definition

Override `is_human_readable` to return `false` for CDR Serializer and Deserializer.

### Benefits

- Correctly represents CDR as a non-human-readable format
- Flexibility in serialization/deserialization between human-readable (JSON/YAML) and binary (CDR) formats

### Example use case

A potential use case would be a `UUID`, that is easier to use as a `String` in a JSON / YAML format, but that can be then converted into its actual representation (byte array)

- `Cargo.toml` 

```toml
[dependencies]
# Created a branch that points to my CDR-encoding branch 
rustdds = { git = "https://github.com/sevnx/RustDDS.git", branch="serde-human-readable-dep" }

# You can see that it doesn't work if you change the version
# rustdds = "0.10.3"

uuid = "1.10.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
```

- `main.rs`

```rust
use rustdds::{no_key, DomainParticipantBuilder, QosPolicyBuilder};
use serde::{Deserialize, Deserializer, Serialize};
use std::{str::FromStr, time::Duration};
use uuid::Uuid as UuidInner;

// We use default Serialization, as it is not an issue here
#[derive(Debug, Default, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize)]
pub struct Uuid([u8; 16]);

impl FromStr for Uuid {
    type Err = uuid::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        UuidInner::from_str(s).map(|uuid| Uuid(uuid.into_bytes()))
    }
}

/// Custom deserialization : we want two kinds of deserialization
/// - From JSON / YAML etc. -> We interpret it as String, creating the Uuid out of it
/// - In DDS network -> We interpret it as its type : a length 16 [u8] byte array
impl<'de> Deserialize<'de> for Uuid {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        // We would expect types like JSON / YAML to be human readable
        // and types or representation like CDR to be non human readable
        if deserializer.is_human_readable() {
            // Interpreted as a String that is converted
            let s = String::deserialize(deserializer)?;
            Uuid::from_str(&s).map_err(|error| serde::de::Error::custom(format!("{error}")))
        } else {
            // Interpreted as its type : byte array
            let bytes: [u8; 16] = <[u8; 16]>::deserialize(deserializer)?;
            Ok(Uuid(bytes))
        }
    }
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct Object {
    pub uuid: Uuid,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Dds Structure
    let domain_participant = DomainParticipantBuilder::new(0).build()?;
    let qos = QosPolicyBuilder::new().build();
    let topic = domain_participant.create_topic(
        "ObjectTopic".to_string(),
        "Object".to_string(),
        &qos,
        rustdds::TopicKind::NoKey,
    )?;
    let publisher = domain_participant.create_publisher(&qos)?;
    let subscriber = domain_participant.create_subscriber(&qos)?;

    // Message
    let json = r#"
    {
        "uuid": "918a5a32-8db3-46fd-810d-6839cf36e684"
    }
    "#;
    let msg: Object = serde_json::from_str(json)?;

    // Create Writer / Reader
    let writer = publisher.create_datawriter_no_key_cdr(&topic, None)?;
    let mut reader: no_key::DataReader<Object> =
        subscriber.create_datareader_no_key_cdr(&topic, None)?;

    // Wait for discovery
    std::thread::sleep(Duration::from_secs(2));
    writer.write(msg, None)?;

    // Wait for write
    std::thread::sleep(Duration::from_secs(1));

    // Read
    let sample = reader.take_next_sample()?.unwrap().into_value().uuid;
    println!("{sample:?}");

    Ok(())
}
```

**Comment by jhelovuo** [comment]
> ## Need definition
> Override `is_human_readable` to return `false` for CDR Serializer and Deserializer.
> 
> ### Benefits
> * Correctly represents CDR as a non-human-readable format

Yes, this is clearly true, and a good reason to make the change.

> * Flexibility in serialization/deserialization between human-readable (JSON/YAML) and binary (CDR) formats

This I do not fully get, even with your example. Are you suggesting that a deserializer could guess its input format based on `is_human_readable`?

**Comment by sevnx** [comment]
> This I do not fully get, even with your example. Are you suggesting that a deserializer could guess its input format based on is_human_readable?

Yes, the `is_human_readable` flag allows to potentially have two formats that we can deserialize : 

- a human readable one, most commonly a **dynamic** representation 
- a non-human readable, **compact** representation

This requires us to write a custom deserialize implementation for our type, where we explicitly have two paths based on `is_human_readable`.

The example just shows that I can load UUID `918a5a32-8db3-46fd-810d-6839cf36e684` from a JSON and convert it to an UUID instead of having to explicitly write the byte array `[145, 138, 90, 50, 141, 179, 70, 253, 129, 13, 104, 57, 207, 54, 230, 132]`.

**Comment by jhelovuo** [comment]
Yes, now I understand better what you mean. There is also a very similar example in the documentation of [`is_human_readable`](https://docs.rs/serde/1.0.210/serde/de/trait.Deserializer.html#method.is_human_readable).

At first glance, it seems very fishy to let the the `Deserialize` implementation to decide, based on a single flag only, how the incoming data should be deserialized. A single `deserialize` implementation should work for _all_ possible serialization formats, so how could we account for all of them?

But for a UUID this could be acceptable, since it has two widely-accepted serialization formats, namely the textual and binary encodings discussed here, and there is also a wide consensus on which format should be used where, and the `is_human_readable` flag is a good approximation of this.

In general, a design like this is really asking for trouble. Now there is some non-obvious behaviour hidden in the (de)serialization of a type, which is supposed to be used as a basic building block of something bigger. The serialization format is changed to something completely different based on a decision hidden in a basic data type. Again, this is mostly fine for UUID, because everyone more or less expects this, but that is an exception to the rule. A timestamp is already a much more tricky, because of a very large collection of serialization formats in use.
