### ISSUE TITLE
Version and breadth of coverage of CDR spec

### ISSUE THREAD

**Issue by PLeVasseur** [jhelovuo/cdr-encoding#3]
Hey there 👋

I saw this in the README.md:
> See [Wikipedia](https://en.wikipedia.org/wiki/Common_Data_Representation) or [specification in Section "9.3 CDR Transfer Syntax"](https://www.omg.org/spec/CORBA/3.4/Interoperability/PDF).

which is a great starting point, and I was specifically curious about current version and level of coverage of the spec.

Thanks for any help! ✌️

**Comment by jhelovuo** [comment]
I have some difficulty in understanding what are you specifically asking here, but I assume it is about the version of the CDR specification we are using.

The linked document is the specification for CORBA 3.0 from 2002, whereas the latest version would be CORBA 3.4 (or 3.3) from 2012. They both contain a section called "CDR Transfer Syntax".  This part of the specification is almost the same in both versions.

The `cdr-encoding` Rust package is essentially a mapping between the [Serde](https://serde.rs/) data model and CDR encoding. As far as this mapping is concerned, I am not aware of any differences between CORBA spec versions 3.0 to 3.4. Please open a issue, if you notice anything that should affect this package.

The level of coverage could be described as implementing the Serde data model. There are features in CDR beyond this, but they are outside of the scope of Serde.

**Comment by PLeVasseur** [comment]
Thanks for the detailed reply! You've answered all my questions 👍 

Maybe most others know these details, but it could be useful to write something like this in the docs / README.md for a newbie like me.

Closing as resolved.
